### ISSUE TITLE
[Request] Delete unused images with dryrun

### ISSUE THREAD

**Issue by Ikes72** [fmartinou/whats-up-docker#218]
Hi,

I use docker trigger with dryrun enabled and i have sometimes a lot of unused images if i don't upgrade quickly my containers and delete this unused images.
So, would it be possible to add an option to delete all unused images except the latest downloaded (latest version)?

Thanks.

**Comment by Ikes72** [comment]
Hi,

Any opinion on my request?

**Comment by fmartinou** [comment]
Hi,

I get your point; I'll try to implement it.

**Comment by fmartinou** [comment]
You can test the feature with the version `fmartinou/whats-up-docker:feature__218_prune_images`
(it will be included to the next release)

To enable it, in addition to the `WUD_TRIGGER_DOCKER_{trigger_name}_DRYRUN=true` env var, you need to enable the prune with the `WUD_TRIGGER_DOCKER_{trigger_name}_PRUNE=true` option

**Comment by Ikes72** [comment]
Hi @fmartinou ,

I have tested the version with the new feature, but i have some errors.

`2023-02-21T20:05:20.441Z 40 name=whats-up-docker hostname=f45b00ee67e7 pid=1 component=watcher.docker.local container=local_speedtest-tracker msg=Error when processing (The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined) v=0

2023-02-21T20:05:20.442Z 30 name=whats-up-docker hostname=f45b00ee67e7 pid=1 component=trigger.mqtt.emqx msg=Add hass device [id=wud_container_local_speedtest-tracker] v=0

2023-02-21T20:05:20.443Z 40 name=whats-up-docker hostname=f45b00ee67e7 pid=1 component=watcher.docker.local container=local_homepage msg=Error when processing (The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined) v=0

2023-02-21T20:05:20.444Z 30 name=whats-up-docker hostname=f45b00ee67e7 pid=1 component=trigger.mqtt.emqx msg=Add hass device [id=wud_container_local_homepage] v=0

2023-02-21T20:05:20.444Z 40 name=whats-up-docker hostname=f45b00ee67e7 pid=1 component=watcher.docker.local container=local_authentik msg=Error when processing (The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined) v=0

2023-02-21T20:05:20.445Z 30 name=whats-up-docker hostname=f45b00ee67e7 pid=1 component=trigger.mqtt.emqx msg=Add hass device [id=wud_container_local_authentik] v=0

2023-02-21T20:05:20.445Z 40 name=whats-up-docker hostname=f45b00ee67e7 pid=1 component=watcher.docker.local container=local_authentik-worker msg=Error when processing (The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined) v=0

2023-02-21T20:05:20.446Z 30 name=whats-up-docker hostname=f45b00ee67e7 pid=1 component=trigger.mqtt.emqx msg=Add hass device [id=wud_container_local_authentik-worker] v=0

2023-02-21T20:05:20.449Z 40 name=whats-up-docker hostname=f45b00ee67e7 pid=1 component=watcher.docker.local msg=Error when processing some containers (Cannot read properties of undefined (reading 'tag')) v=0
` 
Logs at startup:
`2023-02-21T20:16:15.267Z 30 name=whats-up-docker hostname=3f553258d6a0 pid=1 msg=What's up Docker? is starting (version = feature__218_prune_images) v=0

2023-02-21T20:16:15.269Z 30 name=whats-up-docker hostname=3f553258d6a0 pid=1 component=store msg=Load store from (/store/wud.json) v=0

2023-02-21T20:16:15.278Z 30 name=whats-up-docker hostname=3f553258d6a0 pid=1 component=prometheus msg=Init Prometheus module v=0

2023-02-21T20:16:15.334Z 30 name=whats-up-docker hostname=3f553258d6a0 pid=1 component=registry msg=Register all components of kind trigger for provider docker v=0

2023-02-21T20:16:15.780Z 30 name=whats-up-docker hostname=3f553258d6a0 pid=1 component=trigger.docker.local msg=Register with configuration {"dryrun":true,"once":true,"threshold":"major","prune":true,"mode":"simple","simpletitle":"New ${kind} found for container ${name}","simplebody":"Container ${name} running with ${kind} ${local} can be updated to ${kind} ${remote}\n${link}","batchtitle":"${count} updates available"} v=0
`
I have no errors with 6.0.2.

**Comment by fmartinou** [comment]
Hi,

Can you please:
1. cleanup everything before testing the version (in particular the `/store/wud.json` if you mount it as a volume)?
2. enable debug logs (`WUD_LOG_LEVEL=true`)
3. test with `WUD_TRIGGER_DOCKER_{trigger_name}_PRUNE=false and true`

Because I don't correlate your error with the change 🤔 .
If you take a look at the PR, all the changes are wrapped into a `if (this.configuration.prune) {}` and the 1st execution should be the print of the log `Pruning previous tags`, which I don't see in your logs; it seems to fail long before that step.

**Comment by Ikes72** [comment]
Hi,

Here are the logs, after deleting wud.json and PRUNE setting to true:

`2023-02-22T17:27:04.869Z 40 name=whats-up-docker hostname=15b3d79d81ad pid=1 component=watcher.docker.local container=local_homepage msg=Error when processing (The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined) v=0
2023-02-22T17:27:04.870Z 20 name=whats-up-docker hostname=15b3d79d81ad pid=1 component=watcher.docker.local container=local_homepage err={"message":"The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined","name":"TypeError","stack":"TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined\n    at new NodeError (node:internal/errors:387:5)\n    at Function.from (node:buffer:328:9)\n    at Ghcr.authenticate (/home/node/app/registries/providers/ghcr/Ghcr.js:56:31)\n    at Ghcr.callRegistry (/home/node/app/registries/Registry.js:205:54)\n    at Ghcr.getTagsPage (/home/node/app/registries/Registry.js:111:21)\n    at Ghcr.getTags (/home/node/app/registries/Registry.js:88:31)\n    at Docker.findNewVersion (/home/node/app/watchers/providers/docker/Docker.js:517:49)\n    at Docker.watchContainer (/home/node/app/watchers/providers/docker/Docker.js:421:53)\n    at /home/node/app/watchers/providers/docker/Docker.js:395:52\n    at Array.map (<anonymous>)\n    at Docker.watch (/home/node/app/watchers/providers/docker/Docker.js:395:28)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Docker.watchFromCron (/home/node/app/watchers/providers/docker/Docker.js:362:34)","code":"ERR_INVALID_ARG_TYPE"} msg=The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined v=0
2023-02-22T17:27:04.870Z 20 name=whats-up-docker hostname=15b3d79d81ad pid=1 component=watcher.docker.local container=local_homepage msg=Container watched for the first time v=0
2023-02-22T17:27:04.872Z 30 name=whats-up-docker hostname=15b3d79d81ad pid=1 component=trigger.mqtt.emqx msg=Add hass device [id=wud_container_local_homepage] v=0
2023-02-22T17:27:04.873Z 40 name=whats-up-docker hostname=15b3d79d81ad pid=1 component=watcher.docker.local container=local_speedtest-tracker msg=Error when processing (The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined) v=0
2023-02-22T17:27:04.874Z 20 name=whats-up-docker hostname=15b3d79d81ad pid=1 component=watcher.docker.local container=local_speedtest-tracker err={"message":"The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined","name":"TypeError","stack":"TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined\n    at new NodeError (node:internal/errors:387:5)\n    at Function.from (node:buffer:328:9)\n    at Ghcr.authenticate (/home/node/app/registries/providers/ghcr/Ghcr.js:56:31)\n    at Ghcr.callRegistry (/home/node/app/registries/Registry.js:205:54)\n    at Ghcr.getTagsPage (/home/node/app/registries/Registry.js:111:21)\n    at Ghcr.getTags (/home/node/app/registries/Registry.js:88:31)\n    at Docker.findNewVersion (/home/node/app/watchers/providers/docker/Docker.js:517:49)\n    at Docker.watchContainer (/home/node/app/watchers/providers/docker/Docker.js:421:53)\n    at /home/node/app/watchers/providers/docker/Docker.js:395:52\n    at Array.map (<anonymous>)\n    at Docker.watch (/home/node/app/watchers/providers/docker/Docker.js:395:28)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Docker.watchFromCron (/home/node/app/watchers/providers/docker/Docker.js:362:34)","code":"ERR_INVALID_ARG_TYPE"} msg=The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined v=0
2023-02-22T17:27:04.874Z 20 name=whats-up-docker hostname=15b3d79d81ad pid=1 component=watcher.docker.local container=local_speedtest-tracker msg=Container watched for the first time v=0
2023-02-22T17:27:04.874Z 30 name=whats-up-docker hostname=15b3d79d81ad pid=1 component=trigger.mqtt.emqx msg=Add hass device [id=wud_container_local_speedtest-tracker] v=0
2023-02-22T17:27:04.875Z 40 name=whats-up-docker hostname=15b3d79d81ad pid=1 component=watcher.docker.local container=local_authentik msg=Error when processing (The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined) v=0
2023-02-22T17:27:04.875Z 20 name=whats-up-docker hostname=15b3d79d81ad pid=1 component=watcher.docker.local container=local_authentik err={"message":"The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined","name":"TypeError","stack":"TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined\n    at new NodeError (node:internal/errors:387:5)\n    at Function.from (node:buffer:328:9)\n    at Ghcr.authenticate (/home/node/app/registries/providers/ghcr/Ghcr.js:56:31)\n    at Ghcr.callRegistry (/home/node/app/registries/Registry.js:205:54)\n    at Ghcr.getTagsPage (/home/node/app/registries/Registry.js:111:21)\n    at Ghcr.getTags (/home/node/app/registries/Registry.js:88:31)\n    at Docker.findNewVersion (/home/node/app/watchers/providers/docker/Docker.js:517:49)\n    at Docker.watchContainer (/home/node/app/watchers/providers/docker/Docker.js:421:53)\n    at /home/node/app/watchers/providers/docker/Docker.js:395:52\n    at Array.map (<anonymous>)\n    at Docker.watch (/home/node/app/watchers/providers/docker/Docker.js:395:28)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Docker.watchFromCron (/home/node/app/watchers/providers/docker/Docker.js:362:34)","code":"ERR_INVALID_ARG_TYPE"} msg=The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined v=0
2023-02-22T17:27:04.875Z 20 name=whats-up-docker hostname=15b3d79d81ad pid=1 component=watcher.docker.local container=local_authentik msg=Container watched for the first time v=0
2023-02-22T17:27:04.876Z 30 name=whats-up-docker hostname=15b3d79d81ad pid=1 component=trigger.mqtt.emqx msg=Add hass device [id=wud_container_local_authentik] v=0
2023-02-22T17:27:04.876Z 40 name=whats-up-docker hostname=15b3d79d81ad pid=1 component=watcher.docker.local container=local_authentik-worker msg=Error when processing (The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined) v=0
2023-02-22T17:27:04.876Z 20 name=whats-up-docker hostname=15b3d79d81ad pid=1 component=watcher.docker.local container=local_authentik-worker err={"message":"The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined","name":"TypeError","stack":"TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined\n    at new NodeError (node:internal/errors:387:5)\n    at Function.from (node:buffer:328:9)\n    at Ghcr.authenticate (/home/node/app/registries/providers/ghcr/Ghcr.js:56:31)\n    at Ghcr.callRegistry (/home/node/app/registries/Registry.js:205:54)\n    at Ghcr.getTagsPage (/home/node/app/registries/Registry.js:111:21)\n    at Ghcr.getTags (/home/node/app/registries/Registry.js:88:31)\n    at Docker.findNewVersion (/home/node/app/watchers/providers/docker/Docker.js:517:49)\n    at Docker.watchContainer (/home/node/app/watchers/providers/docker/Docker.js:421:53)\n    at /home/node/app/watchers/providers/docker/Docker.js:395:52\n    at Array.map (<anonymous>)\n    at Docker.watch (/home/node/app/watchers/providers/docker/Docker.js:395:28)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Docker.watchFromCron (/home/node/app/watchers/providers/docker/Docker.js:362:34)","code":"ERR_INVALID_ARG_TYPE"} msg=The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined v=0
2023-02-22T17:27:04.876Z 20 name=whats-up-docker hostname=15b3d79d81ad pid=1 component=watcher.docker.local container=local_authentik-worker msg=Container watched for the first time v=0
2023-02-22T17:27:04.877Z 30 name=whats-up-docker hostname=15b3d79d81ad pid=1 component=trigger.mqtt.emqx msg=Add hass device [id=wud_container_local_authentik-worker] v=0
2023-02-22T17:27:04.877Z 20 name=whats-up-docker hostname=15b3d79d81ad pid=1 component=trigger.mqtt.emqx msg=Publish container result to wud/container/local/homepage v=0
2023-02-22T17:27:04.880Z 20 name=whats-up-docker hostname=15b3d79d81ad pid=1 component=trigger.mqtt.emqx msg=Publish container result to wud/container/local/speedtest-tracker v=0
2023-02-22T17:27:04.880Z 20 name=whats-up-docker hostname=15b3d79d81ad pid=1 component=trigger.mqtt.emqx msg=Publish container result to wud/container/local/authentik v=0
2023-02-22T17:27:04.881Z 20 name=whats-up-docker hostname=15b3d79d81ad pid=1 component=trigger.mqtt.emqx msg=Publish container result to wud/container/local/authentik-worker v=0`

**Comment by Ikes72** [comment]
I have the same errors after deleting wud.json and setting PRUNE option to false:

`2023-02-22T17:33:56.177Z 40 name=whats-up-docker hostname=b3290f2680c4 pid=1 component=watcher.docker.local container=local_homepage msg=Error when processing (The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined) v=0
2023-02-22T17:33:56.178Z 20 name=whats-up-docker hostname=b3290f2680c4 pid=1 component=watcher.docker.local container=local_homepage err={"message":"The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined","name":"TypeError","stack":"TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined\n    at new NodeError (node:internal/errors:387:5)\n    at Function.from (node:buffer:328:9)\n    at Ghcr.authenticate (/home/node/app/registries/providers/ghcr/Ghcr.js:56:31)\n    at Ghcr.callRegistry (/home/node/app/registries/Registry.js:205:54)\n    at Ghcr.getTagsPage (/home/node/app/registries/Registry.js:111:21)\n    at Ghcr.getTags (/home/node/app/registries/Registry.js:88:31)\n    at Docker.findNewVersion (/home/node/app/watchers/providers/docker/Docker.js:517:49)\n    at Docker.watchContainer (/home/node/app/watchers/providers/docker/Docker.js:421:53)\n    at /home/node/app/watchers/providers/docker/Docker.js:395:52\n    at Array.map (<anonymous>)\n    at Docker.watch (/home/node/app/watchers/providers/docker/Docker.js:395:28)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Docker.watchFromCron (/home/node/app/watchers/providers/docker/Docker.js:362:34)","code":"ERR_INVALID_ARG_TYPE"} msg=The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined v=0
2023-02-22T17:33:56.178Z 20 name=whats-up-docker hostname=b3290f2680c4 pid=1 component=watcher.docker.local container=local_homepage msg=Container watched for the first time v=0
2023-02-22T17:33:56.180Z 30 name=whats-up-docker hostname=b3290f2680c4 pid=1 component=trigger.mqtt.emqx msg=Add hass device [id=wud_container_local_homepage] v=0
2023-02-22T17:33:56.182Z 40 name=whats-up-docker hostname=b3290f2680c4 pid=1 component=watcher.docker.local container=local_speedtest-tracker msg=Error when processing (The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined) v=0
2023-02-22T17:33:56.182Z 20 name=whats-up-docker hostname=b3290f2680c4 pid=1 component=watcher.docker.local container=local_speedtest-tracker err={"message":"The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined","name":"TypeError","stack":"TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined\n    at new NodeError (node:internal/errors:387:5)\n    at Function.from (node:buffer:328:9)\n    at Ghcr.authenticate (/home/node/app/registries/providers/ghcr/Ghcr.js:56:31)\n    at Ghcr.callRegistry (/home/node/app/registries/Registry.js:205:54)\n    at Ghcr.getTagsPage (/home/node/app/registries/Registry.js:111:21)\n    at Ghcr.getTags (/home/node/app/registries/Registry.js:88:31)\n    at Docker.findNewVersion (/home/node/app/watchers/providers/docker/Docker.js:517:49)\n    at Docker.watchContainer (/home/node/app/watchers/providers/docker/Docker.js:421:53)\n    at /home/node/app/watchers/providers/docker/Docker.js:395:52\n    at Array.map (<anonymous>)\n    at Docker.watch (/home/node/app/watchers/providers/docker/Docker.js:395:28)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Docker.watchFromCron (/home/node/app/watchers/providers/docker/Docker.js:362:34)","code":"ERR_INVALID_ARG_TYPE"} msg=The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined v=0
2023-02-22T17:33:56.182Z 20 name=whats-up-docker hostname=b3290f2680c4 pid=1 component=watcher.docker.local container=local_speedtest-tracker msg=Container watched for the first time v=0
2023-02-22T17:33:56.183Z 30 name=whats-up-docker hostname=b3290f2680c4 pid=1 component=trigger.mqtt.emqx msg=Add hass device [id=wud_container_local_speedtest-tracker] v=0
2023-02-22T17:33:56.183Z 40 name=whats-up-docker hostname=b3290f2680c4 pid=1 component=watcher.docker.local container=local_authentik msg=Error when processing (The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined) v=0
2023-02-22T17:33:56.183Z 20 name=whats-up-docker hostname=b3290f2680c4 pid=1 component=watcher.docker.local container=local_authentik err={"message":"The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined","name":"TypeError","stack":"TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined\n    at new NodeError (node:internal/errors:387:5)\n    at Function.from (node:buffer:328:9)\n    at Ghcr.authenticate (/home/node/app/registries/providers/ghcr/Ghcr.js:56:31)\n    at Ghcr.callRegistry (/home/node/app/registries/Registry.js:205:54)\n    at Ghcr.getTagsPage (/home/node/app/registries/Registry.js:111:21)\n    at Ghcr.getTags (/home/node/app/registries/Registry.js:88:31)\n    at Docker.findNewVersion (/home/node/app/watchers/providers/docker/Docker.js:517:49)\n    at Docker.watchContainer (/home/node/app/watchers/providers/docker/Docker.js:421:53)\n    at /home/node/app/watchers/providers/docker/Docker.js:395:52\n    at Array.map (<anonymous>)\n    at Docker.watch (/home/node/app/watchers/providers/docker/Docker.js:395:28)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Docker.watchFromCron (/home/node/app/watchers/providers/docker/Docker.js:362:34)","code":"ERR_INVALID_ARG_TYPE"} msg=The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined v=0
2023-02-22T17:33:56.183Z 20 name=whats-up-docker hostname=b3290f2680c4 pid=1 component=watcher.docker.local container=local_authentik msg=Container watched for the first time v=0
2023-02-22T17:33:56.184Z 30 name=whats-up-docker hostname=b3290f2680c4 pid=1 component=trigger.mqtt.emqx msg=Add hass device [id=wud_container_local_authentik] v=0
2023-02-22T17:33:56.184Z 40 name=whats-up-docker hostname=b3290f2680c4 pid=1 component=watcher.docker.local container=local_authentik-worker msg=Error when processing (The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined) v=0
2023-02-22T17:33:56.184Z 20 name=whats-up-docker hostname=b3290f2680c4 pid=1 component=watcher.docker.local container=local_authentik-worker err={"message":"The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined","name":"TypeError","stack":"TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined\n    at new NodeError (node:internal/errors:387:5)\n    at Function.from (node:buffer:328:9)\n    at Ghcr.authenticate (/home/node/app/registries/providers/ghcr/Ghcr.js:56:31)\n    at Ghcr.callRegistry (/home/node/app/registries/Registry.js:205:54)\n    at Ghcr.getTagsPage (/home/node/app/registries/Registry.js:111:21)\n    at Ghcr.getTags (/home/node/app/registries/Registry.js:88:31)\n    at Docker.findNewVersion (/home/node/app/watchers/providers/docker/Docker.js:517:49)\n    at Docker.watchContainer (/home/node/app/watchers/providers/docker/Docker.js:421:53)\n    at /home/node/app/watchers/providers/docker/Docker.js:395:52\n    at Array.map (<anonymous>)\n    at Docker.watch (/home/node/app/watchers/providers/docker/Docker.js:395:28)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Docker.watchFromCron (/home/node/app/watchers/providers/docker/Docker.js:362:34)","code":"ERR_INVALID_ARG_TYPE"} msg=The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined v=0
2023-02-22T17:33:56.184Z 20 name=whats-up-docker hostname=b3290f2680c4 pid=1 component=watcher.docker.local container=local_authentik-worker msg=Container watched for the first time v=0
2023-02-22T17:33:56.185Z 30 name=whats-up-docker hostname=b3290f2680c4 pid=1 component=trigger.mqtt.emqx msg=Add hass device [id=wud_container_local_authentik-worker] v=0
2023-02-22T17:33:56.185Z 20 name=whats-up-docker hostname=b3290f2680c4 pid=1 component=trigger.mqtt.emqx msg=Publish container result to wud/container/local/homepage v=0
2023-02-22T17:33:56.187Z 20 name=whats-up-docker hostname=b3290f2680c4 pid=1 component=trigger.mqtt.emqx msg=Publish container result to wud/container/local/speedtest-tracker v=0
2023-02-22T17:33:56.188Z 20 name=whats-up-docker hostname=b3290f2680c4 pid=1 component=trigger.mqtt.emqx msg=Publish container result to wud/container/local/authentik v=0
2023-02-22T17:33:56.188Z 20 name=whats-up-docker hostname=b3290f2680c4 pid=1 component=trigger.mqtt.emqx msg=Publish container result to wud/container/local/authentik-worker v=0`

**Comment by Ikes72** [comment]
I have no error with 6.0.2:

`2023-02-22T17:40:51.881Z 30 name=whats-up-docker hostname=2690d8fc8a4b pid=1 component=trigger.docker.local container=local_authentik-worker msg=Image ghcr.io/goauthentik/server:2023.2.2 pulled with success v=0
2023-02-22T17:40:51.881Z 30 name=whats-up-docker hostname=2690d8fc8a4b pid=1 component=trigger.docker.local container=local_authentik-worker msg=Do not replace the existing container because dry-run mode is enabled v=0
2023-02-22T17:40:51.964Z 30 name=whats-up-docker hostname=2690d8fc8a4b pid=1 component=trigger.docker.local container=local_authentik msg=Image ghcr.io/goauthentik/server:2023.2.2 pulled with success v=0
2023-02-22T17:40:51.964Z 30 name=whats-up-docker hostname=2690d8fc8a4b pid=1 component=trigger.docker.local container=local_authentik msg=Do not replace the existing container because dry-run mode is enabled v=0
2023-02-22T17:40:53.550Z 20 name=whats-up-docker hostname=2690d8fc8a4b pid=1 component=watcher.docker.local container=local_redis msg=Container watched for the first time v=0
2023-02-22T17:40:53.550Z 30 name=whats-up-docker hostname=2690d8fc8a4b pid=1 component=trigger.mqtt.emqx msg=Add hass device [id=wud_container_local_redis] v=0
2023-02-22T17:40:53.551Z 20 name=whats-up-docker hostname=2690d8fc8a4b pid=1 component=trigger.mqtt.emqx msg=Publish container result to wud/container/local/redis v=0
2023-02-22T17:40:53.551Z 30 name=whats-up-docker hostname=2690d8fc8a4b pid=1 component=watcher.docker.local msg=Cron finished (24 containers watched, 0 errors, 2 available updates) v=0`

**Comment by fmartinou** [comment]
Fix released as `6.1.0`
