### ISSUE TITLE
Docker Compose Triggers not updating or emailing

### ISSUE THREAD

**Issue by mattdale77** [fmartinou/whats-up-docker#251]
I can see my docker compose triggers running, however they do not perform any updates. I can see the docker-compose.yml being backed up but there is nothing else in the logs. It's very likely that I've configured things wrong but I can't see what I need to do

      - WUD_TRIGGER_DOCKERCOMPOSE_OFFICE_FILE=/wud/docker-compose/onlyoffice/docker-compose.yml
      - WUD_TRIGGER_DOCKERCOMPOSE_OFFICE_BACKUP=true
      - WUD_TRIGGER_DOCKERCOMPOSE_OFFICE_PRUNE=true
      - WUD_TRIGGER_DOCKERCOMPOSE_OFFICE_ONCE=false

This is the relevant bits of my environment in the WUD container. Am I missing anything?

UPDATE: I got an email through, it was a container with a new update not seen by WUD before. From this I surmise that it (sensibly) only emails on new updates and not those previously noticed. I will remove the email section from my post to prevent cluttering my real issue that they are not being updated by the docker compose trigger

**Comment by mattdale77** [comment]
I don't know if the following is related or not but this a one of the containers detected with a new version which is not being updated

WARN whats-up-docker/watcher.docker.local: Error when processing some containers (Cannot read properties of undefined (reading 'tag'))
INFO whats-up-docker/watcher.docker.local: Cron finished (0 containers watched, 0 errors, 0 available updates)
WARN whats-up-docker/watcher.docker.local: Error when processing (Error: getaddrinfo EAI_AGAIN lscr.io) (container=local_bazarr)
DEBUG whats-up-docker/watcher.docker.local: Error: getaddrinfo EAI_AGAIN lscr.io (container=local_bazarr)
RequestError: Error: getaddrinfo EAI_AGAIN lscr.io
at new RequestError (/home/node/app/node_modules/request-promise-core/lib/errors.js:14:15)
 at Request.plumbing.callback (/home/node/app/node_modules/request-promise-core/lib/plumbing.js:87:29)
 at Request.RP$callback [as _callback] (/home/node/app/node_modules/request-promise-core/lib/plumbing.js:46:31)
 at self.callback (/home/node/app/node_modules/request/request.js:185:22)
 at Request.emit (node:events:513:28)
 at Request.emit (node:domain:489:12)
at Request.onRequestError (/home/node/app/node_modules/request/request.js:877:8)
 at ClientRequest.emit (node:events:513:28)
 at ClientRequest.emit (node:domain:489:12)
 at TLSSocket.socketErrorListener (node:_http_client:494:9)
 at TLSSocket.emit (node:events:513:28)
  at TLSSocket.emit (node:domain:489:12)
 at emitErrorNT (node:internal/streams/destroy:157:8)
 at emitErrorCloseNT (node:internal/streams/destroy:122:3)
 at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by mattdale77** [comment]
I think I found where I was going wrong here. My docker-compose files did not explicitly use the :latest tag. They just use the image name and implied latest. I think this might have resolved my issue. I've hit my pull rate limit so I'll come back at check this later

**Comment by mattdale77** [comment]
This did in fact dive my issue. You need to be explicit with the latest tag
