### ISSUE TITLE
registry errors not well displayed

### ISSUE THREAD

**Issue by r3mi** [fmartinou/whats-up-docker#419]
Hello,
thanks for this project !
Errors in registries are very hard to find in the UI: you have to open each container and check if there is an "error" tab.
For example: following last wud updates, LSCR now requires a github username but this was not mentioned in the changelog (only GHCR). I just realized that my lscr checks have been silently deactivated for weeks. Everything is green in the home page or containers page, until you unfold each container and look for an "error" tab.
Is there a way to display such registry errors more prominently in the UI ? 
thanks,

**Comment by LeonardMeyer** [comment]
I have a similar issue after updating. Despite putting token with/without username I keep getting "Unsupported Registry unknown". 
The logs do not help me figuring out what's wrong, I did as instructed [in the docs](https://fmartinou.github.io/whats-up-docker/#/configuration/registries/lscr/).  I'm on latest and up to date.

 ```
bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    expose:
      - "6767"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /homemedia/apps/bazarr/config:/config
      - /homemedia/medias:/homemedia/medias
    restart: unless-stopped
    labels:
      - wud.tag.include=^\d+\.\d+\.\d+$$
 whatsupdocker:
    image: fmartinou/whats-up-docker
    container_name: wud
    expose:
      - "3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /homemedia/apps/wud/store:/store
      - /etc/docker/docker-compose.yml:/wud/docker-compose.yml
    environment:
      - TZ=Europe/Paris
      - WUD_TRIGGER_DOCKERCOMPOSE_SAFEUPDATE_THRESHOLD=minor
      - WUD_TRIGGER_DOCKERCOMPOSE_SAFEUPDATE_FILE=/wud/docker-compose.yml
      - WUD_TRIGGER_DOCKERCOMPOSE_SAFEUPDATE_PRUNE=True
      - WUD_WATCHER_SAFEUPDATE_WATCHBYDEFAULT=true
      - WUD_WATCHER_SAFEUPDATE_CRON=0 4 * * *
      - WUD_REGISTRY_LSCR_USERNAME=LeonardMeyer
      - WUD_REGISTRY_LSCR_TOKEN=xxxxxxx
      - WUD_LOG_LEVEL=trace
    restart: unless-stopped
```

```
22:57:03.409  WARN whats-up-docker/watcher.docker.safeupdate: Error when processing (Unsupported Registry unknown) (container=safeupdate_bazarr)
22:57:03.410 DEBUG whats-up-docker/watcher.docker.safeupdate: Unsupported Registry unknown (container=safeupdate_bazarr)
    Error: Unsupported Registry unknown
        at getRegistry (/home/node/app/watchers/providers/docker/Docker.js:109:15)
        at Docker.findNewVersion (/home/node/app/watchers/providers/docker/Docker.js:497:34)
        at Docker.watchContainer (/home/node/app/watchers/providers/docker/Docker.js:427:53)
        at /home/node/app/watchers/providers/docker/Docker.js:398:52
        at Array.map (<anonymous>)
        at Docker.watch (/home/node/app/watchers/providers/docker/Docker.js:398:28)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async Docker.watchFromCron (/home/node/app/watchers/providers/docker/Docker.js:362:34)
```

Any ideas @fmartinou ?

**Comment by fmartinou** [comment]
Hi @LeonardMeyer ,

The LSCR registry is no more enabled by default because it needs username/password in order to "auto-update" the container.
So now, you need to explicitly enable it and provide Github credentials to do so.

It's documented there:
https://fmartinou.github.io/whats-up-docker/#/configuration/registries/lscr/

**Comment by LeonardMeyer** [comment]
@fmartinou As said in my previous message, this is exactly what I did. However I just updated to the very last version and it works again 🤷‍♂️

**Comment by jlssmt** [comment]
@fmartinou 
I'm currently migrating watchtower to WUD.
Watchtower is still able to notify me about new images from LSCR without login.
Why WUD isn't?

**Comment by thecoshman** [comment]
I would agree with the general idea here, it would be nice if the main UI could make it clearer when WUD can't check if there's updates for the container. I'm currently having to look at making sure my deployment of WUD can detect updates on some private containers, but I have to check one of the containers I know is using my private ghcr to check the error tab. 

Perhaps something like with how a new version tag is displayed could be used if there's an error, just a super high level warning that there's something off with WUDs monitoring of a container.

**Comment by gitnew12** [comment]
> @fmartinou 
> I'm currently migrating watchtower to WUD.
> Watchtower is still able to notify me about new images from LSCR without login.
> Why WUD isn't? 

I was wondering the same. Even Komodo lets me auto update without login.

**Comment by smithj33** [comment]
> > [@fmartinou](https://github.com/fmartinou)
> > I'm currently migrating watchtower to WUD.
> > Watchtower is still able to notify me about new images from LSCR without login.
> > Why WUD isn't?
> 
> I was wondering the same. Even Komodo lets me auto update without login.

Exactly. LSCR does not require credentials for updating.

**Comment by gitnew12** [comment]
> Exactly. LSCR does not require credentials for updating.

According to the WUD documentation, [LSCR](https://getwud.github.io/wud/#/configuration/registries/lscr/) requires a GitHub personal token, while [GHCR](https://getwud.github.io/wud/#/configuration/registries/ghcr/) does not.

This is **odd** because LSCR isn’t an actual repository; it simply redirects to GHCR, as stated in the  Linuxserver.io [FAQ documentation](https://docs.linuxserver.io/FAQ/):

> LSCR is a vanity url for our images, this is provided to us in collaboration with scarf.sh. It is not a dedicated docker registry, rather a redirection service. As of writing it redirects to GitHub Container Registry (ghcr.io).

**Comment by smithj33** [comment]
> > Exactly. LSCR does not require credentials for updating.
> 
> According to the WUD documentation, [LSCR](https://getwud.github.io/wud/#/configuration/registries/lscr/) requires a GitHub personal token, while [GHCR](https://getwud.github.io/wud/#/configuration/registries/ghcr/) does not.
> 
> This is **odd** because LSCR isn’t an actual repository; it simply redirects to GHCR, as stated in the Linuxserver.io [FAQ documentation](https://docs.linuxserver.io/FAQ/):
> 
> > LSCR is a vanity url for our images, this is provided to us in collaboration with scarf.sh. It is not a dedicated docker registry, rather a redirection service. As of writing it redirects to GitHub Container Registry (ghcr.io).

So I figured out a solution at least for my situation. Add docker.io to your image line in the compose file. So for me it was, image: docker.io/linuxserver/speedtest-tracker:latest

Seems WUD doesn't have an issue pulling it this way.

**Comment by gitnew12** [comment]
> So I figured out a solution at least for my situation. Add docker.io to your image line in the compose file. So for me it was, image: docker.io/linuxserver/speedtest-tracker:latest
> 
> Seems WUD doesn't have an issue pulling it this way.

You could also use `image: ghcr.io/linuxserver/speedtest-tracker:latest`
