### ISSUE TITLE
WUD doesn't detect images

### ISSUE THREAD

**Issue by ajgon** [fmartinou/whats-up-docker#42]
Hey, so I installed 4.1.0 and decided to start from scratch. I removed my old `wud.json` cache and ran the image. However I don't see anything in web-ui now. Logs don't show much except:

```
Jun  6 18:32:13 my-host  [2021-06-06T16:32:13.202Z]  INFO: whats-up-docker/7 on 4ff12f78436d: What's up Docker? is starting (version = 4.1.0)
Jun  6 18:32:13 my-host  [2021-06-06T16:32:13.203Z]  INFO: whats-up-docker/7 on 4ff12f78436d: Init DB (/store/wud.json)
Jun  6 18:32:13 my-host  [2021-06-06T16:32:13.209Z]  INFO: whats-up-docker/7 on 4ff12f78436d: Init Prometheus module
Jun  6 18:32:13 my-host  [2021-06-06T16:32:13.334Z]  INFO: whats-up-docker/7 on 4ff12f78436d: Register component hub of type hub with configuration {}
Jun  6 18:32:13 my-host  [2021-06-06T16:32:13.335Z]  INFO: whats-up-docker/7 on 4ff12f78436d: Register component gcr of type gcr with configuration {"privatekey":"-**********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************\n","clientemail":"whatsupdocker@my-host-307615.iam.gserviceaccount.com"}
Jun  6 18:32:13 my-host  [2021-06-06T16:32:13.713Z]  INFO: whats-up-docker/7 on 4ff12f78436d: Register component my-host of type docker with configuration {"host":"my-host","port":2376,"cafile":"/docker/ssl/docker-ca.pem","keyfile":"/docker/ssl/docker-client-key.pem","certfile":"/docker/ssl/docker-client-cert.pem","socket":"/var/run/docker.sock","cron":"0 * * * *","watchbydefault":true,"watchall":false}
Jun  6 18:32:13 my-host  [2021-06-06T16:32:13.714Z]  INFO: whats-up-docker/7 on 4ff12f78436d: Schedule runner (0 * * * *)
Jun  6 18:32:13 my-host  [2021-06-06T16:32:13.733Z]  INFO: whats-up-docker/7 on 4ff12f78436d: HTTP API exposed on port 3000
Jun  6 18:32:13 my-host  [2021-06-06T16:32:13.890Z]  WARN: whats-up-docker/7 on 4ff12f78436d: No Registry Provider found for image {"id":"596b9e70-c223-4827-960b-ffa0b7a1ea19","watcher":"docker.my-host","registryUrl":"registry.my-host.com","image":"vault","containerName":"vault","repoDigest":"sha256:95d3dadd48ff21fd140ba4b32a0bc765c4ec4a7f5cae78e40a7efac004221c7e","watchDigest":false,"imageId":"sha256:484bc4cbe9e960b0154f2cf49aa7cd1d5fa0ad8f370e48f75ed1ca361eb17445","tag":"6.0.10","versionDate":"2021-06-06T10:27:55.399473116Z","architecture":"amd64","os":"linux","size":1497310558,"includeTags":"^[0-9]\\d*\\.[0-9]\\d*\\.[0-9]\\d*$","isSemver":true,"result":{},"created":"2021-06-06T16:32:13.889Z","updated":"2021-06-06T16:32:13.890Z","toBeUpdated":false}
Jun  6 18:32:13 my-host  (node:7) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
Jun  6 18:32:13 my-host      at getRepoDigest (/home/node/app/watchers/providers/docker/Docker.js:174:36)
Jun  6 18:32:13 my-host      at Docker.mapContainerToImage (/home/node/app/watchers/providers/docker/Docker.js:378:28)
Jun  6 18:32:13 my-host      at processTicksAndRejections (internal/process/task_queues.js:95:5)
Jun  6 18:32:13 my-host      at async Promise.all (index 46)
Jun  6 18:32:13 my-host      at async Docker.getImages (/home/node/app/watchers/providers/docker/Docker.js:306:24)
Jun  6 18:32:13 my-host      at async Docker.watch (/home/node/app/watchers/providers/docker/Docker.js:237:29)
Jun  6 18:32:13 my-host  (Use `node --trace-warnings ...` to show where the warning was created)
Jun  6 18:32:13 my-host  (node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
Jun  6 18:32:13 my-host  (node:7) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Jun  6 18:32:13 my-host  [2021-06-06T16:32:13.943Z]  WARN: whats-up-docker/7 on 4ff12f78436d: No Registry Provider found for image {"id":"27f84eab-63e1-4805-b68e-4b1954dd8149","watcher":"docker.my-host","registryUrl":"quay.io","image":"prometheuscommunity/postgres-exporter","containerName":"postgres-exporter","repoDigest":"sha256:dd9925489909c6660deb17783ec3a45dac82caeb2edd88231883675e817a769a","watchDigest":false,"imageId":"sha256:c93b3cec4e35f2ee7ba7c87c0a7100c7e646172fc1e0f5255bb5f2392ebfd11d","tag":"v0.9.0","versionDate":"2021-03-01T13:12:14.589474197Z","architecture":"amd64","os":"linux","size":16945163,"includeTags":"^v[0-9]\\d*\\.[0-9]\\d\\.[0-9]\\d*$","isSemver":true,"result":{},"created":"2021-06-06T16:32:13.942Z","updated":"2021-06-06T16:32:13.942Z","toBeUpdated":false}
```

Also when I try to do `Watch All` in UI, I get `images.forEach is not a function`.

Looks like some images doesn't have `repoDigests` array - especially the ones created locally (without counterpart on hub) - thus this part:

```js
function getRepoDigest(containerImage) {
    const fullDigest = containerImage.RepoDigests[0];
    const digestSplit = fullDigest.split('@');
    return digestSplit[1];
}
```

fails.

**Comment by fmartinou** [comment]
Hi,
Thanks for the feedback.

You're right; unfortunately I haven't protected this part of code :/

1. `Cannot read property 'split' of undefined` -> I'll protect this code to handle locally built images (even is wud won't report anything interesting for those images)
2. `images.forEach is not a function` -> I'll protect this code to handle case where **0** images have been registered

In the mean time, you can maybe exlude these images from being watched? Or include only the images you want to track?

Using env var `WUD_WATCHER_{watcher_name}_WATCHBYDEFAULT=false` and adding labels on specific containers to watch (`wud.watch=true`) [as mentioned here](https://fmartinou.github.io/whats-up-docker/#/configuration/watchers/docker/)

I try to fix both errors quickly... sorry for the inconvenience :/

**Comment by ajgon** [comment]
No worries, there is absolutely no rush here - I downgraded to 4.0.2 for now, and it works flawlessly :)

**Comment by fmartinou** [comment]
Fixed in version `4.1.1`.

**Comment by ajgon** [comment]
I can confirm that fix worked and WUD is working again - thank you!

However, now my "result tags" are duplicated (i.e. they're shown even if the new version tag is the same as current one). 

![2021-06-06-233456_3530x291_scrot](https://user-images.githubusercontent.com/150545/120940896-24c10b00-c70f-11eb-926e-3c6122a20be4.png)

However the "update" flag (first column) is indicated properly, and also grafana displays everything correctly (i.e. both show only  images which need actual update). 

Personally it's not an issue for me, just asking - is this interface behavior is expected? :)

**Comment by fmartinou** [comment]
Great to see that everything is working well!

Regarding result tags/digests, yes it's expected.
Before, you couldn't know if undefined was related to:
- no update found?
- not watched?
- watch error?

Now it's more clear (I think).
Of course, the toBeUpdated flag computes the appropriate value to easily let you know whether the container can be updated.
